const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
const CART_DECREASE_TOTAL_PRICE = "CART_DECREASE_TOTAL_PRICE";
const CART_INCREASE_TOTAL_PRICE = "CART_INCREASE_TOTAL_PRICE";
const CART_SET_TOTAL_PRICE = "CART_SET_TOTAL_PRICE";
const CART_SET_QUANTITY = "CART_EDIT_QUANTITY";
const CART_SET_DATA = "CART_SET_DATA";
const CART_INIT_EDITED_LIST = "CART_INIT_EDITED_LIST";
const CART_SET_EDITED_LIST = "CART_SET_EDITED_LIST";

export default {
  CART_REMOVE_ITEM,
  CART_DECREASE_TOTAL_PRICE,
  CART_INCREASE_TOTAL_PRICE,
  CART_SET_TOTAL_PRICE,
  CART_SET_QUANTITY,
  CART_SET_DATA,
  CART_INIT_EDITED_LIST,
  CART_SET_EDITED_LIST
};
